### PR TITLE
Allow formatting ranges in jsonc

### PR DESCRIPTION
**Pull request by rotu**
- [X] Run tests
- [X] Update the [`CHANGELOG.md`][1] with a summary of your changes

[1]: https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by rotu** [comment]
I can't figure out why `allRangeLanguages` even exists. Why don't all supported languages allow range formatting? Is it still necessary?

**Comment by rotu** [comment]
@ntotten, you introduced this whitelist. Could you weigh in?

**Comment by ntotten** [comment]
I didn't actually introduce it, I probably moved the code last. Prettier used to only support range formatting on certain languages, if that isn't true anymore happy to take a PR (with tests) removing this flag.

**Comment by rotu** [comment]
Ahhh. Gotcha. I tested it, and it seems that, if prettier doesn't support range formatting in a file, it will just ignore the `--range-start` and `--range-end` options and format the whole file.

**Pull request merged**
