### PR TITLE
Module path can be a dir when loading prettier version

### PR DESCRIPTION
**Pull request by enisdenjo**
It is possible that the `modulePath` argument passed to `loadPrettierVersionFromPackageJson` is already a directory ([as stated in the `prettierPath` documentation](https://github.com/prettier/prettier-vscode#prettierprettierpath)). In that case, the upwards lookup should start from that directory - not its parent.

- [x] Run tests
- [x] Update the [`CHANGELOG.md`](https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md) with a summary of your changes

### CODE REVIEW

**Comment by somebody1234** [comment]
yeah it'd be really great to get this merge, because currently `prettierPath` *does not work*

**Comment by somebody1234** [comment]
well, i guess it works if you point it to `/prettier/index.cjs` - in which case the documentation is incorrect.

**Comment by somebody1234** [comment]
:U

**Comment by enisdenjo** [comment]
Bad bot!

**Comment by joelrbrandt** [comment]
@enisdenjo thanks for contributing this!

@ntotten we'd love to see this merged. We've got branches of our repo on 2.8.8 and 3.1.1, and we'd love to be able to use the same VSCode workspace settings for both versions.

Right now, we have to use this for 3.1.1

```json
{
    "prettier.prettierPath": "${workspaceFolder}/path/to/node_modules/prettier/index.cjs"
}
```

And this for 2.8.8

```json
{
    "prettier.prettierPath": "${workspaceFolder}/path/to/node_modules/prettier/"
}
```

**Comment by enisdenjo** [comment]
Please merge...

**Review by ntotten — APPROVED** [review]

**Pull request merged**
