### PR TITLE
Bumps prettier to version 1.15.1

### PR DESCRIPTION
**Pull request by matt-auckland**
A new major version was released today: https://prettier.io/blog/2018/11/07/1.15.0.html

### CODE REVIEW

**Comment by svipben** [comment]
You should also update `package-lock.json` by running `npm install`.

**Comment by svipben** [comment]
You should also update `package-lock.json` by running `npm install`.

**Comment by CiGit** [comment]
Thanks for your PR!
There is also #619

**Comment by svipben** [comment]
@CiGit I guess this then can be closed since #619 includes tests, package-lock.json, etc.

**Pull request closed without merging**
