### PR TITLE
Use relative path for ignore file

### LINKED ISSUE #279: .prettierignore is not working
I know it has been a long awaited feature but I can't seem to make it work.  
I have a simple .prettierignore config that is consumed and applied as expected from cli, but the extension keeps formatting files in the editor. 

```
app/modules/
app/root/
app/utils/
webpack/
tools/
config/
server/
package.json
```

prettier is installed globally in my setup 

```bash
❯ prettier --v
1.8.2

❯ code --version
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```

Am I doing anything wrong?
Is there any way I can log extension formatting for debug purposes?

### PR DESCRIPTION
**Pull request by azz**
Fixes #279

### CODE REVIEW

**Comment by azz** [comment]
oops, need to be relative to `ignorePath`...

**Comment by CiGit** [comment]
Nice fix, thanks!

**Comment by elsheepo** [comment]
doesn't work for me, even with a relative path.

**Comment by PaulRBerg** [comment]
I still encounter this bug

- VSCode v1.99.3
- Prettier extension v11.0.0

I tried adding all sorts of paths in `.prettierignore`, nothing worked:

```
./tests
./src
*.ts
**/*.ts
```

**Pull request merged**
