### PR TITLE
chore(deps): prettier 2, latest others

### PR DESCRIPTION
**Pull request by AviVahl**
- upgrade all packages and regenerate `yarn.lock` from scratch.
- fixes all `yarn audit` failures.
- re-format code using `prettier@2` defaults.
- fix `mocha@7` warnings regarding deprecated `"useColors"`.
- adjust expected `"jsfile"` result to new trailing comma.

- [x] Run tests
- [x] Update the [`CHANGELOG.md`][1] with a summary of your changes

[1]: https://github.com/prettier/prettier-vscode/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by AviVahl** [comment]
heya @ntotten, any chance you've you time to review this? :)

**Comment by mirshko** [comment]
Status on this PR?

**Comment by AviVahl** [comment]
Ready for review.

**Comment by AviVahl** [comment]
Thanks @lipis. Is a new extension release planned?

**Comment by alexandcote** [comment]
Any ETA on the release date of this nice bump 😃

**Pull request merged**
