### PR TITLE
test for eslint integration

### PR DESCRIPTION
**Pull request by CiGit**
Context #332 

- [x] remove test commit (npm tarball) once fixed in dependency

### CODE REVIEW

**Comment by CiGit** [comment]
Fails as expected

**Comment by CiGit** [comment]
Second commit adds a npm tarball with a patch: prettier/prettier-eslint#161

**Comment by zimme** [comment]
So there was not really a problem with `8.8.0`, however automatically turning off the `prettier/prettier` rule, if found, and still inferring from its rules caused some confusion about the config precedence.

I've reverted that change in `8.8.1` and the behavior should be more as "expected".

**Comment by CiGit** [comment]
I thought about something like this as it was partially respecting the config.

Thanks @zimme , 8.8.1 passes my little test :-)

**Pull request merged**
