### PR TITLE
use bundled prettier if local prettier does not resolve

### PR DESCRIPTION
**Pull request by anisjonischkeit**
This PR is a fix for this issue: https://github.com/prettier/prettier-vscode/issues/522.

### CODE REVIEW

**Comment by CiGit** [comment]
Thanks for your contribution.
I'm not convinced this is the right solution: silently using an other prettier version.

IMHO: If a user specifies a prettier version, they would expect their code be formatted by that given version.

**Comment by anisjonischkeit** [comment]
I didn’t realise you could even specify what version of prettier you want to use. How do you set it?

**Comment by CiGit** [comment]
package.json's (dev)dependencies

**Comment by anisjonischkeit** [comment]
The problem we are having is that our node_modules folder is not in the default location. With the current version of prettier-vscode, it fails silently in this scenario. With the PR, it passes silently. What if we let it pass but display a message saying "Could not find locally installed prettier, maybe try running npm install. Defaulting to bundled prettier."

**Comment by xeoneux** [comment]
Ah! There's already a PR for this! :)

**Comment by jgoux** [comment]
What can we do to move this PR forward?

I'm using yarn `plug and play` feature and there is no node_modules directory, so no local prettier resolved. 😢

**Comment by CiGit** [comment]
Closing in favor of #811

**Pull request closed without merging**
