### PR TITLE
Use prettier-eslint for TypeScript files

### LINKED ISSUE #190: Prettier ESLint should be invoked for TypeScript files
ESLint supports TypeScript files through [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser).

However, when `eslintIntegration` is enabled, this extension will silently skip prettier-eslint for TypeScript files: https://github.com/prettier/prettier-vscode/blob/7431dd3dc8c0e324be98378efcd1a90ce4f547fa/src/PrettierEditProvider.ts#L118

Are you happy for me to raise a PR that changes this, so TypeScript files do run through prettier-eslint?

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes #190

### CODE REVIEW

**Comment by azz** [comment]
Should probably rename `isNonJsParser` to `parserSupportsEslint` or something like that.

**Comment by OliverJAsh** [comment]
@azz I can do that. Is this what is needed to get this PR merged? Any other changes?

**Comment by CiGit** [comment]
Sorry, forgot that one.
What's the outcome if eslint is not configured with typescript parser?
The use case is: migrating from flow to typescript.

**Comment by OliverJAsh** [comment]
@CiGit Good question.

I just tried this on my project by disabling the TS parser in my ESLint config and then invoking prettier-eslint on the file. Prettier runs fine, and the ESLint auto fixes are not applied, presumably because ESLint silently fails when trying to parse the TypeScript syntax. I think this is probably desirable?

**Comment by CiGit** [comment]
This is what **I** would expect. I mostly don't want it to throw. Are configs still inferred ? indent, ...

Any other input?

Maybe rename `isNonJsParser`, it's no more what it means :-)

**Comment by OliverJAsh** [comment]
@CiGit I just tested it and it does infer config still.

I have renamed and inverted `isNonJsParser` to become `doesParserSupportEslint`.

**Comment by CiGit** [comment]
Could you also update prettier-eslint to 7.1 (at least), it overrides the parser. This makes more sens to me :-)
And we should be good to go

**Comment by OliverJAsh** [comment]
@CiGit I can do that but that shouldn't be necessary as part of this PR, as we're already specifying TS as the parser.

**Comment by OliverJAsh** [comment]
@CiGit I just tried upgrading it but the package lock file has loads of redundant changes for some reason—possibly due to an "old" npm version (I'm using 5.0.3).

**Comment by CiGit** [comment]
I think I've done it with 5.4.0.
Promise, I won't look package.json too closely 😄 

I prefer if it's in this PR. The reason is it would change the output between both prettier-eslint for people having the wrong parser.

**Comment by OliverJAsh** [comment]
@CiGit Done!

**Comment by CiGit** [comment]
Thanks !

**Comment by CiGit** [comment]
Ah, already merged, but I've just found out something. 
> prettier.eslintIntegration (default: false) - Javascript only

from the readme. contribution field in package.json should be wrong too.

**Comment by OliverJAsh** [comment]
https://github.com/prettier/prettier-vscode/pull/211

**Pull request merged**
