### PR TITLE
Update Prettier + Update vscode to remove vulnerable dependencies

### PR DESCRIPTION
**Pull request by sibiraj-s**
This removes some vulnerable packages installed in the project.

This should fix the failing tests too.

### CODE REVIEW

**Comment by sibiraj-s** [comment]
Since `flatmap-stream` removed from npm registry I was unable to update the package individually. I regenerate the lock file but may cause unnecessary conflicts while merging multiple PR's hence I used the existing PR which has the vulnerable dependency to update the package

**Comment by sibiraj-s** [comment]
@CiGit  Can you check this out.

**Comment by svipben** [comment]
Good work, really waiting for this PR to be merged since it fixes a lot of TS issues with Prettier.

**Comment by Eldair** [comment]
Can we get this merged?

**Comment by Eldair** [comment]
Ping @CiGit

**Comment by svipben** [comment]
@j-f1 Thanks for merging this PR! Could you please also release a new version by bumping version number and executing `vsce publish`? Thank you!

**Comment by j-f1** [comment]
I don’t think I have publish access unfortunately :/

**Comment by CiGit** [comment]
Published as 1.7.3

And for the rest, I should have some time before next year...

**Comment by CiGit** [comment]
And thank you @sibiraj-s !

**Comment by svipben** [comment]
@CiGit You're back! Thanks!

**Pull request merged**
