### PR TITLE
Docs: update languages for ESLint integration

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by CiGit** [comment]
Thanks. 

@RobinMalfait I usually press **Squash** to have 1 feature -> 1 commit. Merge to keep multiple commits.

**Comment by RobinMalfait** [comment]
@CiGit Gotcha, will use that one in the future to have an even cleaner history ;)

**Comment by CiGit** [comment]
It's just feeling. If a PR has multiple small feature which are not that dependent, I merge.

Side note, I won't be able to make release or code in those next weeks, I'm moving (packing unpacking physical things 😄 )

**Comment by RobinMalfait** [comment]
Haha, call it coincidence! I'm moving too!

**Pull request merged**
