### PR TITLE
Reduce Installation Time

### PR DESCRIPTION
**Pull request by sibiraj-s**
Hi,
I have added few files to vscodeignore so that those files won't be packed by vscode. These files are not needed anyway. This should improve the installation time.

Approximate final build size.(MacOS)

Before: **~20MB**
After: **~16MB**

### CODE REVIEW

**Comment by sibiraj-s** [comment]
@CiGit can you check this too.

**Comment by CiGit** [comment]
Maybe you want to explore:
https://github.com/Microsoft/vscode-extension-samples/blob/master/webpack-sample/README.md

**Comment by sibiraj-s** [comment]
I did setup the same with webpack, It is getting some wierdo errors. I didn't get enough time to work on it so I just made few changes.

**Comment by sibiraj-s** [comment]
I will a webpack PR sometime sooner.

**Comment by sibiraj-s** [comment]
Updated @CiGit .

I will a webpack PR sometime sooner.

**Comment by sibiraj-s** [comment]
test will pass once #658 merged.

**Comment by CiGit** [comment]
Thank you! For all your contributions!

**Pull request merged**
