### PR TITLE
fix "editor.formatOnSaveMode": "modifications"

### LINKED ISSUE #630: "Format Changed Lines" command
When I use "Format on Save", it formats the entire document. This introduces changes on lines I have not touched, making code review much more difficult.

I would like to have the option to check only changed lines, as measured by the active SCM plugin. This would prevent formatting changes from concealing the actual work done in a pull request, while still ensuring that the code I have modified is "Prettier".

I'd be willing to take a shot at this. Please let me know if this would be better handled in the Prettier project or the VS Code project.

### LINKED ISSUE #1562: Support VSCode 1.49 format modified lines feature
VS Code doesn't support this natively. We would only add this if VS Code's edit providers add this type of API.

_Originally posted by @ntotten in https://github.com/prettier/prettier-vscode/issues/630#issuecomment-545127877_

Since version 1.49, VSCode has the option to apply auto-formatting only to modified lines. Maybe its worth revisiting the referenced issue now.

### LINKED ISSUE #1677: Fails to format when "editor.formatOnSaveMode": "modifications" is set
Hello and thanks for releasing and maintaining this wonderful extension! :bowing_man: 

### Summary

Extension fails to format `.component.html` files when VSCode's `"editor.formatOnSaveMode": "modifications"` is set.

### Steps To Reproduce:

1.  Set `"editor.formatOnSaveMode": "modifications"` in VSCode settings
1.  Try to format using extension (on save or via command)

### Expected result

`path/to/file.component.html` file should be formatted.

### Actual result

Status bar shows `Extension 'Prettier - Code Formatter' cannot format file path/to/file.component.html` and file isn't formatted.

### Additional information

Unsetting `"editor.formatOnSaveMode": "modifications"` in VSCode settings fixes the issue. I suspect that the interop between VSCode's edited ranges and prettier's range is broken. The extension should either implement it or state and fail explicitly if this feature isn't supported.

**VS Code Version**:
```shell
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.8-200.fc33.x86_64
```

**Prettier Extension Version**:
`v5.8.0`

**OS and version**:
Fedora `Linux hp 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## Prettier Log Output

This is strange, cause the output doesn't show an error. Perhaps it is incorrect?
```log
["INFO" - 20:50:53] Using config file at '/[redacted path]/.prettierrc.yaml'
["INFO" - 20:50:53] Prettier Options:
{
  "filepath": "/[redacted path]/src/[redacted path]/file.component.html",
  "parser": "angular",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 120,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "jsxSingleQuote": false,
  "trailingComma": "all",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "always",
  "endOfLine": "lf",
  "embeddedLanguageFormatting": "auto"
}
["INFO" - 20:50:53] Formatting completed in 357.514512ms.
```

### LINKED ISSUE #2295: Support VSCode's format modifications feature
Given prettier does support [range formatting](https://prettier.io/docs/en/options.html#range), can this original request be re-opened?
https://github.com/prettier/prettier-vscode/issues/1562

I know the original request was closed due to prettier having issues reported with range formatting, however:
* Have the most severe of these been solved since the original ticket was closed?
* In any case, given this is a published feature prettier supports and is non-default in vscode, can it be implemented within this extension so it can be used if enabled?

Thanks :)

### LINKED ISSUE #2330: Cannon format JSON with comments on save (mode = modifications)
### Summary

I can prettify a json with comments file (say `.vscode/tasks.json`) both from the CLI and using Format Document inside vscode. But when I save the document, the auto-formatter fails with: 

> Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'JSON with Comments'-files

Perhaps this has to do with my `"editor.formatOnSaveMode": "modifications"` setting, but I don't see a clear relationships between this mode and comment support, so I'm reporting it just in case.

### Steps To Reproduce:

1. Execute the following commands in your terminal in order to create and open a test project:

```sh
mkdir /tmp/proj
cd /tmp/proj
git init
mkdir .vscode
touch .vscode/settings.json
code .
```

2. Copy the following in `.vscode/settings.json` and save it.

```json
{
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "modifications",
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

3. Do some modification to settings.json and save it.

### Expected result

Changes are formatted.

### Actual result

Changes aren't formatted. This message is shown in the statusbar:

> Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'JSON with Comments'-files

### Additional information

**VS Code Version**: 1.61.2

**Prettier Extension Version**: 9.0.0

**OS and version**: macOS Big Sur

## Prettier Log Output

```
["INFO" - 4:35:41 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 4:35:41 PM] Extension Version: 9.0.0.
["INFO" - 4:35:47 PM] Formatting file:///private/tmp/proj/.vscode/settings.json
["INFO" - 4:35:47 PM] Using ignore file (if present) at /private/tmp/proj/.prettierignore
["INFO" - 4:35:47 PM] File Info:
{
  "ignored": false,
  "inferredParser": "json"
}
["INFO" - 4:35:47 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 4:35:47 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/private/tmp/proj/.vscode/settings.json",
  "parser": "json"
}
["INFO" - 4:35:47 PM] Formatting completed in 0.04ms.
```

### PR DESCRIPTION
**Pull request by rotu**
fix #630
fix #1562
fix #1677
fix #2295
fix #2330

- [X] Run tests
- [X] Update the [`CHANGELOG.md`][1] with a summary of your changes

[1]: https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by rotu** [comment]
@ntotten could you review this? It’s a *significant* QoL improvement.

**Comment by ntotten** [comment]
This looks great, can you add some tests though and then I will get it merged.

**Comment by rotu** [comment]
I didn't add a test that actually relies on an SCM, but I did add one for formatting multiple ranges, which should test the same code paths.

In the process, I also discovered a bug in Prettier: https://github.com/prettier/prettier/issues/12540

**Comment by ntotten** [comment]
Awesome. Thanks!

**Comment by nickqi-tubi** [comment]
That's a great improvement. However, I testet the latest `v9.5.0`, it seems formatting the modified lines doesn't work.. I'm using the latest VS Code, which is version 1.66.2. Can you double check for that?

**Comment by rotu** [comment]
@nickqi-tubi what's the file type?

**Comment by nickqi-tubi** [comment]
Hi @rotu , the file type is `.ts`

**Comment by rotu** [comment]
> Hi @rotu , the file type is `.ts`

Well, that wrecks my main theory. Maybe you could see if you can reproduce the issue in the prettier web playground? https://prettier.io/playground/

**Pull request merged**
