### PR TITLE
Add an option to suppress popping up the output panel for a failed run

### PR DESCRIPTION
**Pull request by orta**
Should be enough to close https://github.com/prettier/prettier-vscode/issues/168

Allows a user to opt out of the output channel being popped up, TBH it might be worth thinking about making this be the default and allow opting in to showing the output channel on an error. I can't imagine that the errors are inside prettier any more, and I'm willing to bet that VS Code makes it pretty obvious that your source code isn't compiling correctly. Plus you'll see the "prettier x" in the bottom right.

### CODE REVIEW

**Comment by CiGit** [comment]
Hey, thanks for your PR.

I don't think an option for that is a good move.
We could discuss to remove the automatic opening. It's definitely not in prettier's scope to lint your code. `prettier : X` may be enough to say something went wrong
I'll let @RobinMalfait decide on that one ;-)

As I'm working on #243 there are things which will have to change anyway. (Or I'll have to do some dirty checks to keep the same functionalities)

**Comment by RobinMalfait** [comment]
Hey! Thanks for the PR!

I have been annoyed by the popup itself, especially because it doesn't close when the formatting _is_ correct.

The changes I have requested should result in remove some code (Yay!)

Thanks for the PR!

**Comment by RobinMalfait** [comment]
Perfect!
@CiGit can you verify? Code LGTM

**Comment by CiGit** [comment]
@RobinMalfait 
>Always write to the output log (I think this is already the case)

did you mean https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L161 ?
`onWorkspaceRootChange` is quite embarrassing for #243

**Comment by RobinMalfait** [comment]
I was talking about https://github.com/prettier/prettier-vscode/blob/844ecd6820e6ef95bf432dac761fcd0fd4757520/src/PrettierEditProvider.ts#L158

I didn't know the warning message was still used?

**Comment by CiGit** [comment]
Well it seems to be used. And It can be removed I think.

**Comment by orta** [comment]
^ I can't tell if this is you two asking me to amend this PR

**Comment by RobinMalfait** [comment]
@orta Go ahead 😄

**Comment by RobinMalfait** [comment]
@CiGit Cool, thanks for the PR @orta !

**Pull request merged**
