### PR TITLE
Update prettier (1.18.2) and use new approach for extension usage and tests

### PR DESCRIPTION
**Pull request by svipas**
### Dependencies

-   Update all dependencies including Prettier to [1.18.2](https://prettier.io/blog/2019/06/06/1.18.0.html) and run `npm audit fix` because of found vulnerabilities.
-   Update all dependencies in `testEslint` and `testTslint` with `npm audit fix` because of found vulnerabilities.
-   Remove `vscode` dependency and add `@types/vscode` with `vscode-test`, this is a new approach for extension usage [#70175](https://github.com/microsoft/vscode/issues/70175).
-   Add `glob` and `@types/glob` dependencies for `mocha` tests.
-   Remove `cross-env` because it's unnecessary since we are using now `vscode-test`.

### Scripts

-   Create `watch` script for `tsc --watch` and use `compile` script only for compiling with `tsc` without `--watch` flag.
-   Create `pretest` script to compile and install dependencies.
-   Refactor `test` script to run `./out/test/runTest.js` instead of `./node_modules/vscode/bin/test`.
-   Remove `npm run vscode:prepublish` from Travis because of `pretest` script.
-   Change `rootDir` from `.` to `src`.

### Tests

-   Replace `assert.equal` to `assert.strictEqual` because `assert.equal` is deprecated.
-   Refactor `format()` in `format.test.ts` to properly reject if Thenable rejected.
-   Minor refactor for `eslint`, `ignore` and `tslint` tests.
-   Refactor and fix tslint (`testTslint`) and eslint (`testEslint`) configs.

/cc @CiGit @prettier

### CODE REVIEW

**Comment by svipas** [comment]
Seems like these configs in `testEslint` and `testTslint` were wrong and not working correctly. I fixed them by rewriting them to `json` and fixed the issues. `tslint` doesn't respect `prettier/prettier`, instead `prettier` should be used and with the new version of it `extends` should be replaced with `rulesDirectory`. `eslint` config was having `prettier` rules with `semi` false, but outside of `prettier` rules `semi` was defined as `always`. Also, I increased timeouts for both of them since it takes time to format with these integrations.

**Comment by svipas** [comment]
Maybe @CiGit or somebody from the @prettier team could take a look into this PR?

**Comment by nick** [comment]
@svipas is it easy to install your version directly? This is a real pain right now and I'd rather not wait for your PR to be merged

**Comment by svipas** [comment]
@nick I know it's open-source and we have to wait sometimes since everything is free, but it's not first time feedback is delayed. I was thinking of forking this repo and creating a new extension with this PR and who knows maybe even more work in the future. The question is, does it really makes sense since this is an official extension from Prettier? Another way is maybe to ask to add more contributors with permission to merge PRs and release new version.

To answer your question, you can simply fork this repo with my branch and copy-paste whole folder to `.vscode/extensions`, before that, you should also compile the code with `npm run compile`.

**Comment by nick** [comment]
Thanks... though unfortunately I still seem to get the `Cannot find module '../util/ast-utils'` problem when I have `"prettier.eslintIntegration": true`

**Comment by svipas** [comment]
@nick I guess it's because of ESLint 6, some dependencies still aren't updated to support it, so I guess for now you should use 5.*.* version of ESLint. I will keep this PR updated if they will release new versions with ESLint 6 support.

**Comment by David-Else** [comment]
> Another way is maybe to ask to add more contributors with permission to merge PRs and release new version.

It is listed as having **9,527,749 downloads**, that is a lot of people depending on it.

**Comment by NewFuture** [comment]
when will this PR be merged and publish a new version?

**Comment by implicitdef** [comment]
Hi
The prettier upgrade to 1.18 will be welcome.
I have on my hands a project using Prettier 1.18, because of small differences in formatting behavior (https://github.com/prettier/prettier/pull/5979) compared to 1.17, I cannot use the extension at the moment.

**Comment by blueandhack** [comment]
Ping @azz @CiGit @zimme

**Comment by ghengeveld** [comment]
We're currently stuck with `prettier@1.17.0` because 1.17.1 breaks with `prettier-vscode`.

**Comment by DonMcNamara** [comment]
Is there a reason this PR is stalled? Would it be easier to merge if this were just an update of the prettier version to 1.18.* ?

**Comment by svipas** [comment]
Let's wait one more week and if they don't merge it I will fork it and I will create an extension :)

**Comment by svipas** [comment]
As mentioned earlier I'm creating extension which will contains latest Prettier and I will add more features soon for e.g. you can select existing prettier versions from the list and it will be downloaded into extension (bundled) from the VS Code, in this case we will not require additional PRs to update prettier version inside extension, but we can let developer to decide which version to use :) This is will go to the roadmap and when it will be done I don't know, but I can assure you I will always update prettier version in my extension.

Work in progress, but you can keep eye on my fork of this repo here: https://github.com/svipas/prettier-vscode/pull/3. What was changed will be in the changelog and I will share my roadmap. Also, currently extension is not published. I will keep update here in this PR :)

**Comment by ntotten** [comment]
@svipas Please reopen this if you would like and we will get this merged. We have just been added as new contributors to this project and will start to pull in some of these updates. See: https://twitter.com/ntotten/status/1159830358206111744

**Comment by ntotten** [comment]
@svipas I opened the PR with all your changes here #898. Will get them merged soon.

**Pull request closed without merging**
